# This is the global configuration file for Akarin.
# Some options may impact gameplay, so use with caution,
# and make sure you know what each option does before configuring.
# 
# Akarin forums: https://akarin.io/ 

config-version: 1
core:
  keep-alive-response-timeout: 30s
  parallel-mode: 1
  chunk-save-threads: 2
  tick-rate:
    world-time-update-interval: 1s
    keep-alive-packet-send-interval: 15s
    players-info-update-interval: 30s
  thread-safe:
    async-catcher:
      throw-on-caught: true
  players-per-chunk-io-thread: 50
  always-silent-async-timing: false
  primary-thread-priority: 7
  no-chunks-past-world-border: true
  send-light-only-chunk-sections: true
  optimize-chunk-unloading: true
  enable-real-time-ticking: true
  enable-panda-redstone-wire: false
bootstrap:
  extra-local-address: []
alternative:
  modified-server-brand-name: ''
  gc-before-stuck-restart: true
  disable-end-portal-create: false
  force-difficulty-on-hardcore: true
  legacy-versioning-compat: false
  allow-spawner-modify: true
  version-update-interval: 3600s
messages:
  disconnect:
    kick-player: Kicked by an operator.
    ban-player-name: You are banned from this server! %s %s
    ban-reason: "\nReason: "
    ban-expires: "\nYour ban will be removed on "
    ban-player-ip: Your IP address is banned from this server! %s %s
    kick-player-duplicate-login: You logged in from another location
    kick-player-timeout-keep-alive: Timed out
    player-quit-server: §e%s left the game
  connect:
    player-join-server: §e%s joined the game
    renamed-player-join-server: §e%s (formerly known as %s) joined the game
